### ISSUE TITLE
Can you Make 1.12.2 Version?

### ISSUE THREAD

**Issue by Shadowliezx** [LexManos/CobbleForDays#11]
Hey This very Good Mod can you make version for 1.12.2 ?

**Comment by RainbowTabitha** [comment]
it says completed but i cant find the file. also neoforge port for 1.21. forge is dead.

**Comment by LexManos** [comment]
Neo will never happen. Forge is not dead.
1.12.2 is not needed as TinyProgression or whatever it was back then, exists and has this in it.

**Comment by RainbowTabitha** [comment]
Can you name any big mods on Forge @LexManos ?

I think its more dead then Quilt right now.

Im not trying to be rude just im curious what mods are still on Forge Forge

**Comment by LexManos** [comment]
You do realize you're asking the author of Forge if he wants to move to a platform that is run by people who slander, abuse, and lie about me? Ya fuck that. As for what mods, no honestly I dont know because I dont follow the 'big' mods. Its all a ego contest over who can make the most drama. I'm just here making cool things with little drama.
